springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:exchangedb

exchanger:
  allowed:
    currencies: USD,PLN
  imported:
    currencies: USD
  base:
    currency: PLN
  rate:
    api:
      url: "https://api.nbp.pl/api/exchangerates/rates/c"