springdoc:
  swagger-ui:
    enabled: false
exchanger:
  allowed:
    currencies: USD,PLN
  imported:
    currencies: USD
  base:
    currency: PLN
  rate:
    api:
      url: "https://api.nbp.pl/api/exchangerates/rates/c"
spring:
  liquibase:
    enabled: false